# Generated by Django 3.2 on 2021-04-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.CharField(choices=[('Web', 'Web'), ('Document', 'Document'), ('Enterprise', 'Enterprise'), ('Component', 'Component')], default='', max_length=50),
        ),
    ]
